apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: client2-cicd-cors
  namespace: client2
config:
  credentials: false
  exposed_headers: null
  headers: null
  max_age: null
  methods:
  - GET
  - HEAD
  - PUT
  - PATCH
  - POST
  - DELETE
  - OPTIONS
  - TRACE
  - CONNECT
  origins:
  - '*'
  preflight_continue: false
  private_network: false
plugin: cors