name: CI-Konnect
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  KONNECT_API_TOKEN: ${{ secrets.KONNECT_API_TOKEN }}
  KONNECT_CONTROL_PLANE: ${{ vars.KONNECT_CONTROL_PLANE }}
  KONNECT_REGION: ${{ vars.KONNECT_REGION }}
jobs:
  konnect-devportal:
    runs-on: self-hosted
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Deploy
      - name: Konnect | Deploy API Product and Publish it in the Dev Portal
        run: |
          echo -e "* Creating API product 'MyHttpbin-CICD'"
          productId=$(http --ignore-stdin --raw '{"name":"MyHttpbin-CICD", "description":"A simple REST API service based on https://httpbin.apim.eu"}' POST https://$KONNECT_REGION.api.konghq.com/v2/api-products Authorization:"Bearer $KONNECT_API_TOKEN"  | jq -r '.id')
          echo 'productId='$productId
          portalId=$(http --ignore-stdin https://$KONNECT_REGION.api.konghq.com/konnect-api/api/portals Authorization:"Bearer $KONNECT_API_TOKEN" | jq -r '.data[0].id')
          echo 'portalId='$portalId
          controlPlane=$(http --ignore-stdin https://$KONNECT_REGION.api.konghq.com/v2/runtime-groups Authorization:"Bearer $KONNECT_API_TOKEN" | jq -r --arg control_plane "$KONNECT_CONTROL_PLANE" '.data[] | select(.name == $ARGS.named.control_plane) | .id')
          echo 'controlPlane='$controlPlane
          serviceId=$(http --ignore-stdin https://$KONNECT_REGION.api.konghq.com/v2/runtime-groups/$controlPlane/core-entities/services  Authorization:"Bearer $KONNECT_API_TOKEN" | jq -r '.data[] | select(.name | test("^httproute.client2") ) | .id')
          echo 'serviceId='$serviceId
          raw='{"name":"v1", "publish_status":"published", "gateway_service": {"runtime_group_id":"'$controlPlane'", "id":"'$serviceId'"}}'
          echo "raw"=$raw
          versionId=$(http --ignore-stdin --raw "$raw" POST https://$KONNECT_REGION.api.konghq.com/v2/api-products/$productId/product-versions Authorization:"Bearer $KONNECT_API_TOKEN" | jq -r '.id')
          echo 'versionId='$versionId
          echo -e "* Push 'MyHttpbin-CICD' specification"
          spec=$(base64 -i myhttpbin.json)
          raw='{"name":"myhttpbin.json", "content":"'$spec'"}'
          http --quite --ignore-stdin --raw "$raw" POST https://$KONNECT_REGION.api.konghq.com/v2/api-products/$productId/product-versions/$versionId/specifications  Authorization:"Bearer $KONNECT_API_TOKEN"
          echo -e "* Publish API product 'MyHttpbin-CICD'"
          raw='{"portal_ids": ["'$portalId'"]}'
          http -v --ignore-stdin --raw "$raw" PATCH https://$KONNECT_REGION.api.konghq.com/v2/api-products/$productId  Authorization:"Bearer $KONNECT_API_TOKEN"

