name: CI-Konnect
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  KONNECT_API_TOKEN: ${{ secrets.KONNECT_API_TOKEN }}
  
jobs:
  konnect:
    runs-on: self-hosted
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Deploy
      - name: Konnect | Deploy API Product and Publish it in the Dev Portal
        run: |
          echo -e "* Creating API product 'MyHttpbin-CICD'"
          productId=$(http --ignore-stdin --raw '{"name":"MyHttpbin-CICD", "description":"A simple REST API service based on https://httpbin.apim.eu"}' POST https://eu.api.konghq.com/v2/api-products Authorization:"Bearer $KONNECT_API_TOKEN"  | jq -r '.id')
          echo 'productId=' $productId
          echo -e "* Get Portal Id"
          portalId=$(http https://eu.api.konghq.com/konnect-api/api/portals Authorization:"Bearer $KONNECT_API_TOKEN" | jq -r '.data[0].id')
          echo 'portalId=' $portalId
          echo -e "* Adding new version to API product 'MyHttpbin-CICD'"
