name: CI-Konnect
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  KONNECT_API_TOKEN: ${{ secrets.KONNECT_API_TOKEN }}
  KONNECT_REGION: ${{ env.KONNECT_REGION }}
  KONNECT_CONTROL_PLANE: ${{ env.KONNECT_CONTROL_PLANE }}

jobs:
  konnect:
    runs-on: self-hosted
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Deploy
      - name: Deploy API Product and Publish it in the Dev Portal
        run: |
          echo -e "* Creating API product 'MyHttpbin-CICD'"
          description="A simple REST API service based on https://httpbin.apim.eu"
          productId=$(http POST https://$KONNECT_REGION.api.konghq.com/v2/api-products name="MyHttpbin-CICD" "description=$description" Authorization:"Bearer $KONNECT_API_TOKEN" | jq -r '.id')
          echo 'productId' $productId
