name: CI-Konnect
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  KONNECT_API_TOKEN: ${{ secrets.KONNECT_API_TOKEN }}
  
jobs:
  konnect:
    runs-on: self-hosted
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Deploy
      - name: Konnect | Deploy API Product and Publish it in the Dev Portal
        run: |
          echo -e "* Creating API product 'MyHttpbin-CICD'"
          description="A simple REST API service based on https://httpbin.apim.eu"
          http --raw '{"name":"MyHttpbin-CICD", "description":"$description"}' POST https://eu.api.konghq.com/v2/api-products Authorization:"Bearer kpat_t80qn4BYpmTeLJ3MU78lYf1Wcv1wFf4V5scnKRKSYc9ANxNPi"
          echo 'productId' $productId
